USE `es_extended`;

CREATE TABLE IF NOT EXISTS `ammos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `owner` TEXT NOT NULL,
  `hash` TEXT NOT NULL,
  `count` INT NOT NULL DEFAULT 0,

  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `inventories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `owner` TEXT NOT NULL,
  `type` TEXT DEFAULT NULL,
  `data` LONGTEXT NOT NULL,

  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `inventories_itemdata` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` TEXT NOT NULL,
  `description` TEXT DEFAULT NULL,
  `weight` INT NOT NULL DEFAULT 0,
  `closeOnUse` TINYINT NOT NULL DEFAULT 0,
  `max` INT NOT NULL DEFAULT 100,

  PRIMARY KEY (`id`)
);

ALTER TABLE `items` ADD COLUMN `description` MEDIUMTEXT NOT NULL DEFAULT 'No item description';

INSERT INTO `items` (`name`, `label`, `weight`, `limit`, `rare`, `can_remove`, `description`) VALUES
	('WEAPON_ADVANCEDRIFLE', 'Advanced Rifle', 4.5, 1, 0, 1, 'Rifle Mermisi Kullanır.'),
	('WEAPON_APPISTOL', 'AP Pistol', 1.1, 1, 0, 1, 'Tabanca Mermisi Kullanır.'),
	('WEAPON_ASSAULTRIFLE', 'Assault Rifle', 4.2, 1, 0, 1, 'Rifle Mermisi Kullanır.'),
	('WEAPON_ASSAULTSHOTGUN', 'Assault Shotgun', 3.5, 1, 0, 1, 'Pompalı Mermisi Kullanır.'),
	('WEAPON_ASSAULTSMG', 'Assault SMG', 3, 1, 0, 1, 'SMG Mermisi Kullanır.'),
	('WEAPON_AUTOSHOTGUN', 'Auto Shotgun', 3.7, 1, 0, 1, 'Pompalı Mermisi Kullanır.'),
	('WEAPON_BALL', 'Beyzbol Topu', 0.2, 1, 0, 1, ''),
	('WEAPON_BAT', 'Beyzbol Sopası', 1.5, 1, 0, 1, ''),
	('WEAPON_BATTLEAXE', 'Savaş Baltası', 3, 1, 0, 1, ''),
	('WEAPON_BOTTLE', 'Bottle', 1, 1, 0, 1, ''),
	('WEAPON_BULLPUPRIFLE', 'Bullpup Rifle', 4.2, 1, 0, 1, 'Rifle Mermisi Kullanır.'),
	('WEAPON_BULLPUPSHOTGUN', 'Bullpup Shotgun', 3.9, 1, 0, 1, 'Pompalı Mermisi Kullanır.'),
	('WEAPON_BZGAS', 'BZ Gas', 1.5, 10, 0, 1, ''),
	('WEAPON_CARBINERIFLE', 'Carbine Rifle', 4.3, 1, 0, 1, 'Rifle Mermisi Kullanır.'),
	('WEAPON_COMBATMG', 'Combat MG', 4.6, 1, 0, 1, 'SMG Mermisi Kullanır.'),
	('WEAPON_COMBATPDW', 'Combat PDW', 3.7, 1, 0, 1, 'SMG Mermisi Kullanır.'),
	('WEAPON_COMBATPISTOL', 'Combat Pistol', 3, 1, 0, 1, 'Tabanca Mermisi Kullanır.'),
	('WEAPON_COMPACTLAUNCHER', 'Compact Launcher', 2, 1, 0, 1, ''),
	('WEAPON_COMPACTRIFLE', 'Compact Rifle', 3.7, 1, 0, 1, 'Rifle Mermisi Kullanır.'),
	('WEAPON_CROWBAR', 'Levye', 0.5, 1, 0, 1, ''),
	('WEAPON_DAGGER', 'Hançer', 1.5, 1, 0, 1, ''),
	('WEAPON_DBSHOTGUN', 'Double Barrel Shotgun', 3.2, 1, 0, 1, 'Pompalı Mermisi Kullanır.'),
	('WEAPON_DIGISCANNER', 'Digiscanner', 1, 1, 0, 1, ''),
	('WEAPON_DOUBLEACTION', 'Double Action Revolver', 2.8, 1, 0, 1, 'Tabanca Mermisi Kullanır.'),
	('WEAPON_FIREEXTINGUISHER', 'Yangın Söndürücü', 10, 1, 0, 1, ''),
	('WEAPON_FIREWORK', 'Firework Launcher', 1, 1, 0, 1, ''),
	('WEAPON_FLARE', 'İşaret Fişeği', 1, 1, 0, 1, ''),
	('WEAPON_FLAREGUN', 'İşaret Fişeği Silahı', 1.8, 1, 0, 1, ''),
	('WEAPON_FLASHLIGHT', 'El Feneri', 1, 1, 0, 1, ''),
	('WEAPON_GARBAGEBAG', 'ÇÖP TORBASI', 1, 1, 0, 1, ''),
	('WEAPON_GOLFCLUB', 'Golf Sopası', 3.3, 1, 0, 1, ''),
	('WEAPON_GRENADE', 'El Bombası', 0.3, 10, 0, 1, ''),
	('WEAPON_GUSENBERG', 'Gusenberg', 2.8, 1, 0, 1, 'SMG Mermisi Kullanır.'),
	('WEAPON_HAMMER', 'Çekiç', 0.5, 1, 0, 1, ''),
	('WEAPON_HANDCUFFS', 'Kelepçe', 0.5, 1, 0, 1, ''),
	('WEAPON_HATCHET', 'Balta', 2.5, 1, 0, 1, ''),
	('WEAPON_HEAVYPISTOL', 'Heavy Pistol', 3.2, 1, 0, 1, 'Tabanca Mermisi Kullanır.'),
	('WEAPON_HEAVYSHOTGUN', 'Heavy Shotgun', 4.2, 1, 0, 1, 'Pompalı Mermisi Kullanır.'),
	('WEAPON_HEAVYSNIPER', 'Heavy Sniper', 5.8, 1, 0, 1, 'Sniper Mermisi Kullanır.'),
	('WEAPON_HOMINGLAUNCHER', 'Homing Launcher', 1, 1, 0, 1, ''),
	('WEAPON_KNIFE', 'Bıçak', 0.5, 1, 0, 1, ''),
	('WEAPON_KNUCKLE', 'Muşta', 1, 1, 0, 1, ''),
	('WEAPON_MACHETE', 'Pala', 1, 1, 0, 1, ''),
	('WEAPON_MACHINEPISTOL', 'Machine Pistol', 2.8, 1, 0, 1, 'Tabanca Mermisi Kullanır.'),
	('WEAPON_MARKSMANPISTOL', 'Marksman Pistol', 3, 1, 0, 1, 'Tabanca Mermisi Kullanır.'),
	('WEAPON_MARKSMANRIFLE', 'Marksman Rifle', 6, 1, 0, 1, 'Sniper Mermisi Kullanır.'),
	('WEAPON_MG', 'MG', 4.2, 1, 0, 1, 'Rifle Mermisi Kullanır.'),
	('WEAPON_MICROSMG', 'Micro SMG', 3.8, 1, 0, 1, 'SMG Mermisi Kullanır.'),
	('WEAPON_MINIGUN', 'Minigun', 1, 1, 0, 1, ''),
	('WEAPON_MINISMG', 'Mini SMG', 2.5, 1, 0, 1, 'SMG Mermisi Kullanır.'),
	('WEAPON_MOLOTOV', 'Molotof', 1, 1, 0, 1, ''),
	('WEAPON_MUSKET', 'Musket', 2.8, 1, 0, 1, 'Pompalı Mermisi Kullanır.'),
	('WEAPON_NIGHTSTICK', 'Police Baton', 1, 1, 0, 1, ''),
	('WEAPON_PETROLCAN', 'Benzin Bidonu', 3, 1, 0, 1, ''),
	('WEAPON_PIPEBOMB', 'Pipe Bomb', 1, 1, 0, 1, ''),
	('WEAPON_PISTOL', 'Pistol', 2.2, 1, 0, 1, 'Tabanca Mermisi Kullanır.'),
	('WEAPON_PISTOL50', 'Police .50', 2.5, 1, 0, 1, 'Tabanca Mermisi Kullanır.'),
	('WEAPON_POOLCUE', 'Pool Cue', 1, 1, 0, 1, ''),
	('WEAPON_PROXMINE', 'C4', 1, 10, 0, 1, ''),
	('WEAPON_PUMPSHOTGUN', 'Pump Shotgun', 3.5, 1, 0, 1, 'Pompalı Mermisi Kullanır.'),
	('WEAPON_RAILGUN', 'Rail Gun', 5.2, 1, 0, 1, 'Rifle Mermisi Kullanır.'),
	('WEAPON_REVOLVER', 'Revolver', 3, 1, 0, 1, 'Tabanca Mermisi Kullanır.'),
	('WEAPON_RPG', 'RPG', 8, 1, 0, 1, ''),
	('WEAPON_SAWNOFFSHOTGUN', 'Sawn Off Shotgun', 2.8, 1, 0, 1, 'Pompalı Mermisi Kullanır.'),
	('WEAPON_SMG', 'SMG', 3.8, 1, 0, 1, 'SMG Mermisi Kullanır.'),
	('WEAPON_SMOKEGRENADE', 'Smoke Gernade', 0.5, 10, 0, 1, ''),
	('WEAPON_SNIPERRIFLE', 'Sniper Rifle', 6.2, 1, 0, 1, 'Sniper Mermisi Kullanır.'),
	('WEAPON_SNOWBALL', 'Kar Topu', 1, 10, 0, 1, ''),
	('WEAPON_SNSPISTOL', 'SNS Pistol', 2.4, 1, 0, 1, 'Tabanca Mermisi Kullanır.'),
	('WEAPON_SPECIALCARBINE', 'Special Rifle', 3.6, 1, 0, 1, 'Rifle Mermisi Kullanır.'),
	('WEAPON_STICKYBOMB', 'C4', 2.5, 10, 0, 1, ''),
	('WEAPON_STINGER', 'Stinger', 1, 1, 0, 1, ''),
	('WEAPON_STUNGUN', 'Police Taser', 1, 1, 0, 1, ''),
	('WEAPON_SWITCHBLADE', 'Sustalı', 1.6, 1, 0, 1, ''),
	('WEAPON_VINTAGEPISTOL', 'Vintage Pistol', 2.4, 1, 0, 1, 'Tabanca Mermisi Kullanır.'),
	('WEAPON_WRENCH', 'İngiliz Anahtarı', 2, 1, 0, 1, ''),
	('AMMO_PISTOL', 'Tabanca Mermisi', 10, 100, 0, 1, 'İçinde 30 adet tabanca mermisi bulunan mermi kutusu.'),
	('AMMO_PISTOL_LARGE', 'Tabanca Mermisi Large', 10, 100, 0, 1, 'İçinde 60 adet tabanca mermisi bulunan mermi kutusu.'),
	('AMMO_RIFLE', 'Rifle Mermisi', 10, 100, 0, 1, 'İçinde 45 adet rifle mermisi bulunan mermi kutusu.'),
	('AMMO_RIFLE_LARGE', 'Rifle Mermisi Large', 10, 100, 0, 1, 'İçinde 65adet rifle mermisi bulunan mermi kutusu.'),
	('AMMO_SHOTGUN', 'Pompalı Mermisi', 10, 100, 0, 1, 'İçinde 12 adet Pompalı mermisi bulunan mermi kutusu.'),
	('AMMO_SHOTGUN_LARGE', 'Pompalı Mermisi Large', 10, 100, 0, 1, 'İçinde 18 adet Pompalı mermisi bulunan mermi kutusu.'),
	('AMMO_SMG', 'SMG Mermisi', 10, 100, 0, 1, 'İçinde 45 adet SMG mermisi bulunan mermi kutusu.'),
	('AMMO_SMG_LARGE', 'SMG Mermisi Large', 10, 100, 0, 1, 'İçinde 56 adet SMG mermisi bulunan mermi kutusu.'),
	('AMMO_SNIPER', 'Sniper Mermisi', 10, 100, 0, 1, 'İçinde 10 adet Sniper mermisi bulunan mermi kutusu.'),
	('AMMO_SNIPER_LARGE', 'Sniper Mermisi Large', 10, 100, 0, 1, 'İçinde 15 adet Sniper mermisi bulunan mermi kutusu.'),
    ('cash', 'Dinheiro', 0, 9999999999, 0, 1, '');