USE `es_extended`;

CREATE TABLE IF NOT EXISTS `ammos` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `owner` TEXT NOT NULL,
    `hash` TEXT NOT NULL,
    `count` INT NOT NULL DEFAULT 0,

    PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `inventories` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `owner` TEXT NOT NULL,
    `type` TEXT DEFAULT NULL,
    `data` LONGTEXT NOT NULL,

    PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `inventories_itemdata` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `name` TEXT NOT NULL,
    `description` TEXT DEFAULT NULL,
    `weight` INT NOT NULL DEFAULT 0,
    `closeOnUse` TINYINT NOT NULL DEFAULT 0,
    `max` INT NOT NULL DEFAULT 100,

    PRIMARY KEY (`id`)
);

#ALTER TABLE `items` ADD COLUMN (`limit` INT NOT NULL DEFAULT 10, `description` MEDIUMTEXT NOT NULL DEFAULT 'No item description');

INSERT INTO `items` (`name`, `label`, `weight`, `limit`, `rare`, `can_remove`, `description`) VALUES
('WEAPON_ADVANCEDRIFLE', 'Metralhadora Avançada', 4.5, 1, 0, 1, 'Usa munições de tipo "Rifle"'),
('WEAPON_APPISTOL', 'Pistola AP', 1.1, 1, 0, 1, 'Usa munições de tipo "Pistol"'),
('WEAPON_ASSAULTRIFLE', 'Metralhadora de Assalto', 4.2, 1, 0, 1, 'Usa munições de tipo "Rifle"'),
('WEAPON_ASSAULTSHOTGUN', 'Espingarda de Assalto', 3.5, 1, 0, 1, 'Usa munições de tipo "Shotgun"'),
('WEAPON_ASSAULTSMG', 'Sub-Metralhadora de Assalto', 3, 1, 0, 1, 'Usa munições de tipo "SMG"'),
('WEAPON_AUTOSHOTGUN', 'Shotgun Automática', 3.7, 1, 0, 1, 'Usa munições de tipo "Shotgun"'),
('WEAPON_BALL', 'Bola de beisebol', 0.2, 1, 0, 1, ''),
('WEAPON_BAT', 'Beyzbol Sopası', 1.5, 1, 0, 1, ''),
('WEAPON_BATTLEAXE', 'Taco de beisebol', 3, 1, 0, 1, ''),
('WEAPON_BOTTLE', 'Garrafa', 1, 1, 0, 1, ''),
('WEAPON_BULLPUPRIFLE', 'Metralhadora Bullpup', 4.2, 1, 0, 1, 'Usa munições de tipo "Rifle"'),
('WEAPON_BULLPUPSHOTGUN', 'Espingarda Bullpup', 3.9, 1, 0, 1, 'Usa munições de tipo "Shotgun"'),
('WEAPON_BZGAS', 'Gás BZ', 1.5, 10, 0, 1, ''),
('WEAPON_CARBINERIFLE', 'Espingarda de carabina', 4.3, 1, 0, 1, 'Usa munições de tipo "Rifle"'),
('WEAPON_COMBATMG', 'MG de Combate', 4.6, 1, 0, 1, 'Usa munições de tipo "SMG"'),
('WEAPON_COMBATPDW', 'PDW de Combate', 3.7, 1, 0, 1, 'Usa munições de tipo "SMG"'),
('WEAPON_COMBATPISTOL', 'Pistola de Combate', 3, 1, 0, 1, 'Usa munições de tipo "Pistol"'),
('WEAPON_COMPACTLAUNCHER', 'Lançador compato', 2, 1, 0, 1, ''),
('WEAPON_COMPACTRIFLE', 'Metralhadora compata', 3.7, 1, 0, 1, 'Usa munições de tipo "Rifle"'),
('WEAPON_CROWBAR', 'Pé-de-cabra', 0.5, 1, 0, 1, ''),
('WEAPON_DAGGER', 'Punhal', 1.5, 1, 0, 1, ''),
('WEAPON_DBSHOTGUN', 'Espingarda de cano duplo', 3.2, 1, 0, 1, 'Usa munições de tipo "Shotgun"'),
('WEAPON_DIGISCANNER', 'Digiscanner', 1, 1, 0, 1, ''),
('WEAPON_DOUBLEACTION', 'Revólver de dupla ação', 2.8, 1, 0, 1, 'Usa munições de tipo "Pistol"'),
('WEAPON_FIREEXTINGUISHER', 'Extintor de incêndio', 10, 1, 0, 1, ''),
('WEAPON_FIREWORK', 'Bazuca de foguetes', 1, 1, 0, 1, ''),
('WEAPON_FLARE', 'Sinalização', 1, 1, 0, 1, ''),
('WEAPON_FLAREGUN', 'Pistola de Sinalizador', 1.8, 1, 0, 1, ''),
('WEAPON_FLASHLIGHT', 'Lanterna', 1, 1, 0, 1, ''),
('WEAPON_GARBAGEBAG', 'Saco de Lixo', 1, 1, 0, 1, ''),
('WEAPON_GOLFCLUB', 'Taco de golf', 3.3, 1, 0, 1, ''),
('WEAPON_GRENADE', 'Granada', 0.3, 10, 0, 1, ''),
('WEAPON_GUSENBERG', 'Gusenberg', 2.8, 1, 0, 1, 'Usa munições de tipo "SMG"'),
('WEAPON_HAMMER', 'Martelo', 0.5, 1, 0, 1, ''),
('WEAPON_HANDCUFFS', 'Algemas', 0.5, 1, 0, 1, ''),
('WEAPON_HATCHET', 'Machado', 2.5, 1, 0, 1, ''),
('WEAPON_HEAVYPISTOL', 'Pistola pesada', 3.2, 1, 0, 1, 'Usa munições de tipo "Pistol"'),
('WEAPON_HEAVYSHOTGUN', 'Espingarda pesada', 4.2, 1, 0, 1, 'Usa munições de tipo "Shotgun"'),
('WEAPON_HEAVYSNIPER', 'Sniper pesada', 5.8, 1, 0, 1, 'Usa munições de tipo "Sniper"'),
('WEAPON_HOMINGLAUNCHER', 'Bazuca teleguiada', 1, 1, 0, 1, ''),
('WEAPON_KNIFE', 'Faca', 0.5, 1, 0, 1, ''),
('WEAPON_KNUCKLE', 'Soco-Inglês', 1, 1, 0, 1, ''),
('WEAPON_MACHETE', 'Machete', 1, 1, 0, 1, ''),
('WEAPON_MACHINEPISTOL', 'Pistola de Máquina', 2.8, 1, 0, 1, 'Usa munições de tipo "Pistol"'),
('WEAPON_MARKSMANPISTOL', 'Pistola de Marksman', 3, 1, 0, 1, 'Usa munições de tipo "Pistol"'),
('WEAPON_MARKSMANRIFLE', 'Metralhadora de Marksman', 6, 1, 0, 1, 'Usa munições de tipo "Sniper"'),
('WEAPON_MG', 'MG', 4.2, 1, 0, 1, 'Usa munições de tipo "Rifle"'),
('WEAPON_MICROSMG', 'Micro SMG', 3.8, 1, 0, 1, 'Usa munições de tipo "SMG"'),
('WEAPON_MINIGUN', 'Minigun', 1, 1, 0, 1, ''),
('WEAPON_MINISMG', 'Mini SMG', 2.5, 1, 0, 1, 'Usa munições de tipo "SMG"'),
('WEAPON_MOLOTOV', 'Coquetel molotov', 1, 1, 0, 1, ''),
('WEAPON_MUSKET', 'Mosquete', 2.8, 1, 0, 1, 'Usa munições de tipo "Shotgun"'),
('WEAPON_NIGHTSTICK', 'Bastão de Polícia', 1, 1, 0, 1, ''),
('WEAPON_PETROLCAN', 'Galão de combustível', 3, 1, 0, 1, ''),
('WEAPON_PIPEBOMB', 'Bomba caseira', 1, 1, 0, 1, ''),
('WEAPON_PISTOL', 'Pistola', 2.2, 1, 0, 1, 'Usa munições de tipo "Pistol"'),
('WEAPON_PISTOL50', 'Pistola .50', 2.5, 1, 0, 1, 'Usa munições de tipo "Pistol"'),
('WEAPON_POOLCUE', 'Taco de bilhar', 1, 1, 0, 1, ''),
('WEAPON_PROXMINE', 'Mina de proximidade', 1, 10, 0, 1, ''),
('WEAPON_PUMPSHOTGUN', 'Espingarda Pump', 3.5, 1, 0, 1, 'Usa munições de tipo "Shotgun"'),
('WEAPON_RAILGUN', 'Rail Gun', 5.2, 1, 0, 1, 'Usa munições de tipo "Rifle"'),
('WEAPON_REVOLVER', 'Revólver', 3, 1, 0, 1, 'Usa munições de tipo "Pistol"'),
('WEAPON_RPG', 'Bazuca RPG', 8, 1, 0, 1, ''),
('WEAPON_SAWNOFFSHOTGUN', 'Espingarda Sawn-Off', 2.8, 1, 0, 1, 'Usa munições de tipo "Shotgun"'),
('WEAPON_SMG', 'SMG', 3.8, 1, 0, 1, 'Usa munições de tipo "SMG"'),
('WEAPON_SMOKEGRENADE', 'Granda de fumaça', 0.5, 10, 0, 1, ''),
('WEAPON_SNIPERRIFLE', 'Metralhadora Sniper', 6.2, 1, 0, 1, 'Usa munições de tipo "Sniper"'),
('WEAPON_SNOWBALL', 'Bola de neve', 1, 10, 0, 1, ''),
('WEAPON_SNSPISTOL', 'Pistola SNS', 2.4, 1, 0, 1, 'Usa munições de tipo "Pistol"'),
('WEAPON_SPECIALCARBINE', 'Metralhadora Especial', 3.6, 1, 0, 1, 'Usa munições de tipo "Rifle"'),
('WEAPON_STICKYBOMB', 'Bomba C4', 2.5, 10, 0, 1, ''),
('WEAPON_STINGER', 'Stinger', 1, 1, 0, 1, ''),
('WEAPON_STUNGUN', 'Arma de eletrochoque', 1, 1, 0, 1, ''),
('WEAPON_SWITCHBLADE', 'Canivete', 1.6, 1, 0, 1, ''),
('WEAPON_VINTAGEPISTOL', 'Pistola de Vintage', 2.4, 1, 0, 1, 'Usa munições de tipo "Pistol"'),
('WEAPON_WRENCH', 'Chave Inglesa', 2, 1, 0, 1, ''),
('AMMO_PISTOL', 'Caixa de munições de Pistola', 10, 100, 0, 1, 'Caixa de munições com 30 balas da categoria "Pistola".'),
('AMMO_PISTOL_LARGE', 'Pacote de munições de Pistola', 10, 100, 0, 1, 'Pacote de munições com 60 balas da categoria "Pistola".'),
('AMMO_SHOTGUN', 'Caixa de munições de Espingarda', 10, 100, 0, 1, 'Caixa de munições com 12 balas da categoria "Espingarda".'),
('AMMO_SHOTGUN_LARGE', 'Pacote de munições de Espingarda', 10, 100, 0, 1, 'Pacote de munições com 18 balas da categoria "Espingarda".'),
('AMMO_SMG', 'Caixa de munições de Sub-Metralhadora', 10, 100, 0, 1, 'Pacote de munições com 45 balas da categoria "Sub-Metralhadora".'),
('AMMO_SMG_LARGE', 'Pacote de munições de Sub-Metralhadora', 10, 100, 0, 1, 'Pacote de munições com 56 balas da categoria "Sub-Metralhadora".'),
('AMMO_RIFLE', 'Caixa de munições de Metralhadora', 10, 100, 0, 1, 'Caixa de munições com 45 balas da categoria "Metralhadora".'),
('AMMO_RIFLE_LARGE', 'Pacote de munições de Metralhadora', 10, 100, 0, 1, 'Caixa de munições com 65 balas da categoria "Metralhadora".'),
('AMMO_SNIPER', 'Caixa de munições de Sniper', 10, 100, 0, 1, 'Pacote de munições com 10 balas da categoria "Sniper".'),
('AMMO_SNIPER_LARGE', 'Pacote de munições de Sniper', 10, 100, 0, 1, 'Pacote de munições com 15 balas da categoria "Sniper".'),
('cash', 'Dinheiro', 0, 2147483647, 0, 1, '');